# Generated by Django 6.0.4 on 2026-04-28 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FuelStation', fields=[
                ('id', models.BigAutoField(
                    auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('opis_id', models.IntegerField(
                        unique=True)), ('name', models.CharField(
                            max_length=255)), ('address', models.CharField(
                                max_length=255)), ('city', models.CharField(
                                    max_length=100)), ('state', models.CharField(
                                        max_length=2)), ('rack_id', models.IntegerField(
                                            blank=True, null=True)), ('retail_price', models.FloatField()), ('lat', models.FloatField(
                                                blank=True, null=True)), ('lon', models.FloatField(
                                                    blank=True, null=True)), ('is_custom', models.BooleanField(
                                                        default=False)), ('geocoded', models.BooleanField(
                                                            default=False)), ('created_at', models.DateTimeField(
                                                                auto_now_add=True)), ], options={
                'indexes': [
                    models.Index(
                        fields=[
                            'lat', 'lon'], name='stations_fu_lat_be7092_idx'), models.Index(
                        fields=['state'], name='stations_fu_state_5f6afa_idx'), models.Index(
                        fields=['retail_price'], name='stations_fu_retail__5512c5_idx')], }, ), ]
